#!/bin/bash

IMAGE_NAME=cerberus-tox
VOLUME_NAME=cerberus-tox

cd "$(dirname ${0})"

podman build -t $IMAGE_NAME --build-arg uid=$(id -u) . || exit 1
[ -z "$(podman volume ls -q --filter 'name=$VOLUME_NAME')" ] \
    && podman volume create $VOLUME_NAME
podman run --rm -v "$VOLUME_NAME:/src/.tox" $IMAGE_NAME "${@}"
EXIT_CODE=$?

cd -
exit $EXIT_CODE
