"""
This module contains the error messages issued by the Cerberus Validator.
The test suite uses this module as well.
"""
ERROR_SCHEMA_MISSING = "validation schema missing"
ERROR_SCHEMA_FORMAT = "'{}' is not a schema, must be a dict"
ERROR_DOCUMENT_MISSING = "document is missing"
ERROR_DOCUMENT_FORMAT = "'{}' is not a document, must be a dict"
ERROR_UNKNOWN_RULE = "unknown rule '{}' for field '{}'"
ERROR_DEFINITION_FORMAT = "schema definition for field '{}' must be a dict"
ERROR_UNKNOWN_FIELD = "unknown field"
ERROR_REQUIRED_FIELD = "required field"
ERROR_UNKNOWN_TYPE = "unrecognized data-type '{}'"
ERROR_BAD_TYPE = "must be of {} type"
ERROR_MIN_LENGTH = "min length is {}"
ERROR_MAX_LENGTH = "max length is {}"
ERROR_UNALLOWED_VALUES = "unallowed values {}"
ERROR_UNALLOWED_VALUE = "unallowed value {}"
ERROR_ITEMS_LIST = "length of list should be {}"
ERROR_READONLY_FIELD = "field is read-only"
ERROR_MAX_VALUE = "max value is {}"
ERROR_MIN_VALUE = "min value is {}"
ERROR_EMPTY_NOT_ALLOWED = "empty values not allowed"
ERROR_NOT_NULLABLE = "null value not allowed"
ERROR_REGEX = "value does not match regex '{}'"
ERROR_DEPENDENCIES_FIELD = "field '{}' is required"
ERROR_DEPENDENCIES_FIELD_VALUE = "field '{}' is required with values: {}"
